export default {
  name: "transfersSection",
  title: "Traslados",
  type: "document",
  fields: [
    { name: "title", title: "Título", type: "string", initialValue: "Servicios de Traslados" },
    { name: "subtitle", title: "Subtítulo", type: "string", initialValue: "Conectamos Bogotá con comodidad y seguridad. Desde el aeropuerto hasta servicios por horas para tus necesidades." },
  { name: "airportTabTitle", title: "Título opción Aeropuerto", type: "string", initialValue: "Servicios Aeropuerto" },
  { name: "hourlyTabTitle", title: "Título opción Por Horas", type: "string", initialValue: "Servicios por Horas" },
    {
      name: "airportTransfer",
      title: "Traslado Aeropuerto (único)",
      type: "object",
      fields: [
        { name: "title", title: "Título", type: "string" },
        { name: "description", title: "Descripción", type: "string" },
        { name: "price", title: "Precio", type: "string" },
        { name: "duration", title: "Duración", type: "string" },
        { name: "capacity", title: "Capacidad", type: "string" },
        { name: "image", title: "Imagen (asset)", type: "image", options: { hotspot: true } },
        { name: "imageUrl", title: "Imagen (URL externa)", type: "url" },
        { name: "features", title: "Características", type: "array", of: [{ type: "string" }] },
      ],
      preview: { select: { title: "title", subtitle: "price" } },
    },
    {
      name: "hourlyTransfer",
      title: "Servicio por Horas (único)",
      type: "object",
      fields: [
        { name: "title", title: "Título", type: "string" },
        { name: "description", title: "Descripción", type: "string" },
        { name: "price", title: "Precio", type: "string" },
        { name: "minHours", title: "Mínimo de horas", type: "string" },
        { name: "capacity", title: "Capacidad", type: "string" },
        { name: "image", title: "Imagen (asset)", type: "image", options: { hotspot: true } },
        { name: "imageUrl", title: "Imagen (URL externa)", type: "url" },
        { name: "features", title: "Características", type: "array", of: [{ type: "string" }] },
      ],
      preview: { select: { title: "title", subtitle: "price" } },
    },
  ],
}
